config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  post '/', to: 'api#api_help', as: 'api_help'
  post '/api', to: 'api#api_request', as: 'api_request'

  post '/introduction', to: 'sessions#introduction', as: 'introduction'
  post '/continue', to: 'sessions#continue', as: 'continue'

  post '/seek_rabbit', to: 'sessions#seek_rabbit', as: 'seek_rabbit'
  post '/switch_language', to: 'sessions#switch_language', as: 'switch_language'
  post '/switch_colored_hint', to: 'sessions#switch_colored_hint', as: 'switch_colored_hint'
  post '/vote_rabbit', to: 'sessions#vote_rabbit', as: 'vote_rabbit'

  post '/current_speech', to: 'speeches#current_speech', as: 'current_rabbit_speech'
  post '/answer_speech', to: 'speeches#answer_speech', as: 'answer_rabbit_speech'
  post '/carrot_recognizer', to: 'application#carrot_recognizer', as: 'carrot_recognizer'

  mount ActionCable.server => '/cable'
  get '/cv', to: 'application#display_cv', as: 'display_cv'
  get '*path', to: 'application#wrong_path', via: :all

end

app/views/elements/_bush.html.haml
= turbo_frame_tag "bush-#{index}-#{session.uuid}",class:"bush-container", style:"--top-position:#{bush[:top]}%;--left-position:#{bush[:left]}%" do
    - unless bush[:scotty]
        = image_tag "behind_bush/#{rand(1..6)}.png", class: "behind-bush"
        = image_tag "bush.png", class: "bush", data: { action: "mousedown->bush#toggleBush"}
    - else 
        = render partial: "elements/scotty_hide", locals: {session_rabbit: bush[:scotty]}

app/views/elements/_carrot_recognizer.html.haml
#carrot-recognizer{ data: {controller: "carrot-recognizer", session_uuid: session[:uuid] }}
  .file-drop
    %p= t(".drop_carrot")
    .file-preview{ data: {target: "carrot-recognizer.filePreview",action: "dragover->carrot-recognizer#handleDragOver drop->carrot-recognizer#handleDrop" }}
      %img{ data: {target: "carrot-recognizer.previewImage" }}

app/views/elements/_carrot_sign.html.haml
.carrot-sign

app/views/elements/_colored_hint.html.haml
= turbo_frame_tag "colored-hint-container" do
    .text-block.colored-hint__text
        %span= t(".colored")
        %span.colored-word= t(".hints")
    .bool-switch__block{data:{controller: "colored-hint", session_uuid: session.uuid}}
        %input{type: "checkbox", name: "colored_hint", class: "bool-switch__checkbox", id: "colored_hint", checked: session.colored_hint, data: {action: "change->colored-hint#switchColoredHint"}}
        %label{for: "colored_hint", class: "bool-switch__label"}

app/views/elements/_configuration.html.haml
= turbo_frame_tag "configuration", class:"#{session.finished? ? "animated" : ""}" do
    = render partial: "elements/colored_hint", locals: {session: session}
    = render partial: "elements/language_select", locals: {session: session}

app/views/elements/_language_select.html.haml
#language-select{data: {controller: "language-select", session_uuid: session.uuid}}
    - Session.languages.keys.each do |language|
        .language-option{data: {action:"click->language-select#switchLanguage", language: language}, class:"#{session.language == language ? 'selected' : ''}"}
            = image_tag "flags/#{language}.png", alt: "flag-#{language}", class: "language-flag"

app/views/elements/_mobile_cache.html.haml
#mobile_cache{data:{controller: "mobile"}}
    .mobile_text=t(".mobile_warning")

app/views/elements/_rabbit_found.html.haml
= turbo_frame_tag "#{session_rabbit.rabbit.underscore_name}-#{session_rabbit.session.uuid}", class: "#{session_rabbit.rabbit.underscore_name} rabbit-found #{out ? "go-home" : ""}", data:{controller: "rabbit", session_uuid: session_rabbit.session.uuid,rabbit_uuid: session_rabbit.uuid, target: "end.rabbitFound" }, style:"--animation-delay:#{rand(3..25)}s" do
    = turbo_frame_tag "#{session_rabbit.uuid}-#{session_rabbit.session.uuid}-speech", class: "rabbit-speech" do
        - if session_rabbit.session.status != "finished"
            = render partial: "elements/speech_status", locals: {session_rabbit: session_rabbit}
    .rabbit-container
        %span.rabbit-name= session_rabbit.rabbit.name
        = image_tag "rabbits/#{session_rabbit.rabbit.underscore_name}.png", class: "rabbit-image", alt: "#{session_rabbit.rabbit.underscore_name}"

app/views/elements/_rabbit_transcriptor.html.haml
#rabbit-transcriptor{data: {controller: "rabbit-transcriptor", session_uuid: session_rabbit.session.uuid, rabbit_uuid: session_rabbit.uuid}}
    #message{data:{target: "rabbit-transcriptor.message"}}
    #paws-board
        #left-board
        #paw-keys
            = image_tag "paws/paw_0.png", class: "paw", data: {action: "click->rabbit-transcriptor#addPawToMessage", paw: "0"}
            = image_tag "paws/paw_1.png", class: "paw",data: {action: "click->rabbit-transcriptor#addPawToMessage", paw: "1"}
            = image_tag "paws/paw_2.png", class: "paw",data: {action: "click->rabbit-transcriptor#addPawToMessage", paw: "2"}
            = image_tag "paws/paw_3.png", class: "paw",data: {action: "click->rabbit-transcriptor#addPawToMessage", paw: "3"}
            = image_tag "paws/paw_4.png", class: "paw",data: {action: "click->rabbit-transcriptor#addPawToMessage", paw: "4"}
        #right-board
            = image_tag "speech/light_speech_bubble.png", class: "talk", data: {action: "click->rabbit-transcriptor#sendMessage"}

app/views/elements/_scotty_hide.html.haml
= turbo_frame_tag "scotty-#{session_rabbit.session.uuid}",data: { action: "click->bush#toggleBehindBush", uuid: session_rabbit.uuid, key: session_rabbit.key }, class: "behind-bush hide" do
    = image_tag "rabbits/scotty.png"
= image_tag "bush.png", class: "bush", data: { action: "mousedown->bush#toggleBush"}

app/views/elements/_speech_bubble.html.haml
.speech-bubble{class: classes}
    .speech-chunks.speech-text
        - chunks.each_with_index do |chunk,index|
            .speech-chunk
                - if chunk.is_a?(String)
                    .text-block
                        -if colored_words.any?
                            - chunk.split(/\s+/).each do |word|
                                - if colored_words.include?(word)
                                    %span.colored-word=word
                                - else 
                                    %span= word
                        - else
                            %span= chunk
                - elsif chunk.is_a?(Array)
                    - chunk.each do |paws|
                        .paws
                            - paws.each_char do |paw|
                                = image_tag "paws/paw_#{paw}.png", class: "paw"
                .chunk-hidder{class: "chunk-#{index}",style: "--nth:#{index}"}
    .speech-answers
        - if answers.present?
            - answers.each do |answer|
                .button--little{class: "#{answer == "no_thanks" ? "no-thanks" : ""}",data:{action: "click->rabbit#answerSpeech", answer: answer}}= I18n.t("answer-#{answer}")
        - elsif !no_answer
            .button--little{data:{action: "click->rabbit#answerSpeech", answer: "ok"}}= I18n.t("answer-ok")

app/views/elements/_speech_status.html.haml
- unless session_rabbit.speech_status == "no_speech"
    .speech-status{class:"#{session_rabbit.speech_status}", data:{action: "click->rabbit#requestCurrentSpeech"}}

app/views/elements/_title_screen.html.haml
= turbo_stream_from("session-#{session.uuid}")
=turbo_frame_tag "title-screen", data:{controller: "title-screen", target: "title-screen.titleScreen"} do
    .title-screen__container{data:{target: "title-screen.titleContainer"}}
        .title-screen__title-container
            .title-screen__title= t("the_ten_rabbits")
        .title-screen__author-container    
            .title-screen__author= t("author")
    - if session.initialized?
        = button_to t('.begin'), introduction_path(session_uuid: session.uuid),disabled:true, class:"button--big title-screen__button", data: {target: "title-screen.titleButton",action: "click->title-screen#launchIntroduction"} 
    - else
        = button_to t('.continue'), continue_path(session_uuid: session.uuid),disabled:true, class: "button--big title-screen__button", data: {target: "title-screen.titleButton",action: "click->title-screen#continueSession"}
    .title-screen__warning-container{data: {target: "title-screen.titleWarning"}}
        .information-container
            .information__title= t("warning")
            .information__text
                .information__exclamation.left
                    =svg_tag("exclamation")
                = t(".warning_text")
                .information__exclamation.right
                    =svg_tag("exclamation")